name: CI for Roopdeepassign2

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Use the latest Node.js version

      - name: Install dependencies
        run: npm install
        working-directory: roopdeepassign2

      - name: Run tests
        run: npm test
        working-directory: roopdeepassign2

      - name: Build the project
        run: npm run build
        working-directory: roopdeepassign2
